@startuml
'title Diagrama de Casos de Uso
left to right direction
actor Utilizador as user

package "Sistema RAG" {
    usecase "Importar Ficheiros de Texto" as UC1
    usecase "Processar e Indexar Informação em Diferentes Bases de Dados" as UC2
    usecase "Efetuar Perguntas" as UC3
    usecase "Visualizar Resultados das Perguntas" as UC4
    usecase "Fornecer Métricas" as UC5
}

user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5

@enduml
