@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Utilizador
participant Sistema

Utilizador -> Sistema : Envia Ficheiro
Sistema -> Sistema : Guarda Ficheiro
Sistema -> Utilizador : Envia Mensagem de Confirmação

@enduml