@startuml

autonumber
Actor Utilizador as user

participant ChatController as controller
participant Neo4jService as neo4jService

participant "Azure/OpenAI" as azureOpenAI

database "Base de dados" as db

activate user
user -> controller : POST: /chat/import-file?filename=<name>

activate controller

controller -> neo4jService : Envia Ficheiro
activate neo4jService

neo4jService --> neo4jService : Divide Ficheiro em chunks (tamanho N)
loop até serem processados todos os chunks
neo4jService -> azureOpenAI : Processa Informação Conforme Necessário
activate azureOpenAI
azureOpenAI --> neo4jService : Envia Chunk Processado
end loop
deactivate azureOpenAI

neo4jService -> db : Envia Informação Processada
activate db
db --> db : Guarda Informação Processada
db --> neo4jService : Mensagem de Confirmação
deactivate db

neo4jService --> controller : Mensagem de Confirmação
deactivate neo4jService

controller --> user : Mensagem de Confirmação
deactivate controller

@enduml