@startuml

autonumber
Actor Utilizador as user

participant ChatController as controller
participant AzureService as azureService
participant Neo4jService as neo4jService

participant "Azure/OpenAI" as azureOpenAI

database "AzureAiSearch" as azureAiSearch
database "Neo4j" as neo4j

activate user
user -> controller : POST: /chat/import-file?filename=<name>

activate controller

controller -> azureService : Envia Ficheiro
activate azureService
azureService -> azureAiSearch : Envia Ficheiro

activate azureAiSearch
azureAiSearch --> azureAiSearch : Guarda o Ficheiro
azureAiSearch --> azureService : Mensagem de Confirmação
deactivate azureAiSearch

azureService --> controller : Mensagem de Confirmação
deactivate azureService
controller -> neo4jService : Envia Ficheiro
activate neo4jService

neo4jService -> azureOpenAI : Envia Ficheiro para Processamento
activate azureOpenAI
azureOpenAI -> neo4jService : Envia Ficheiro Processado
deactivate azureOpenAI

neo4jService -> neo4j : Envia Entidades e Relações
activate neo4j
neo4j --> neo4j : Guarda Entidades e Relações
neo4j --> neo4jService : Mensagem de Confirmação
deactivate neo4j

neo4jService --> controller : Mensagem de Confirmação
deactivate neo4jService

controller --> user : Mensagem de Confirmação
deactivate controller

@enduml