@startuml
autonumber 

participant "ChatController" as chatController
participant "AzureService" as azureService

database "AzureAiSearch" as azureAiSearch

chatController -> azureService : Caminho Ficheiro
activate chatController
activate azureService
azureService --> azureService : Devide Ficheiro em Chunks (tamanho N)
loop Até serem processados todos os chunks
    azureService -> azureAiSearch : Envia Chunk
    activate azureAiSearch
    azureAiSearch --> azureAiSearch : Guarda Chunk
    azureAiSearch --> azureService : Mensagem De Confirmação
end loop
deactivate azureAiSearch
azureService --> chatController : Mensagem de Confirmação
deactivate chatController



@enduml