@startuml

autonumber
Actor Utilizador as user

participant ChatController as controller
participant "X Service" as service

participant "LLM" as llm

database "X Base de dados" as db

activate user
user -> controller : POST: /chat/import-file?filename=<name>

activate controller

controller -> service : Envia Ficheiro
activate service

service --> service : Divide Ficheiro em chunks (tamanho N)
loop até serem processados todos os chunks
service -> llm : Processa Informação Conforme Necessário
activate llm
llm --> service : Envia Chunk Processado
end loop
deactivate llm

service -> db : Envia Informação Processada
activate db
db --> db : Guarda Informação Processada
db --> service : Mensagem de Confirmação
deactivate db

service --> controller : Mensagem de Confirmação
deactivate service

controller --> user : Mensagem de Confirmação
deactivate controller

@enduml