@startuml

title Carregamento de Documentos para Base de Dados Neo4j
autonumber

Actor Utilizador as user
participant Sistema as sys
entity "Azure/LLM" as llm
database "Base de Dados" as db 

activate user
user -> sys : Fornece Documentos

activate sys 
sys --> sys: Divide documentos em chunks
loop até todos os chunks forem analisados
sys -> llm : Fornece chunk, instruções e contexto de respostas anteriores
activate llm
llm --> sys : Devolve lista de entidades e relações (JSON)
deactivate llm
sys -> sys: Adiciona resposta ao contexto
end loop

sys -> db : Armazena na base de dados
activate db
db --> sys : Confirmação
deactivate db

sys --> user : Confirmação
deactivate sys


@enduml