@startuml
title Perguntas ao Sistema
autonumber

Actor Utilizador as user
participant Sistema as sys
entity "Azure/LLM" as llm
database "Base de Dados" as db 

activate user
user -> sys : Faz pergunta em linguagem natural

activate sys

sys -> db: Pede o schema da base de dados

activate db
db --> sys : Devolve o schema
deactivate db

sys -> llm: Fornece o schema, pergunta e pede para converter em query
activate llm
llm --> sys: Devolve query
deactivate llm

sys -> db: Faz query
activate db
db --> sys : Devolve resultados da query
deactivate db
sys -> llm : Fornece resultados da query e pede uma resposta formatada
activate llm
llm --> sys: Fornece resposta
deactivate llm
sys --> user : Fornece resposta 
deactivate sys
 

@enduml